package com.lhind.internshipfinalproject.mapper;

import com.lhind.internshipfinalproject.dto.UserDTO;
import com.lhind.internshipfinalproject.entity.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public abstract class UserMapper {

    // Ignore "id" when converting from DTO to entity since it's generated by the database.
    @Mapping(target = "id", ignore = true)
    public abstract User toEntity(UserDTO userDTO);

    // For converting from entity to DTO, no extra mapping is needed if names match.
    public abstract UserDTO toDTO(User user);
}
